### ISSUE TITLE
[Feature Request] Web UI - Remote Control

### ISSUE THREAD

**Issue by DynaZor** [Nenirey/AWGG#13]
Hi!
I would really LOVE to use your program.
But it lacks one key feature I need;
A Remote Control Web UI.
I use an Ubuntu machine as a Home Media Server which also does the downloads.
I want to be able to add (batch) links to it from any other machine through a web UI,
similar to qBittorent.

Is this doable?
If not, or may take a long time,
can you please suggest me another Download Manager which does have that?

Thanks and lots of love <3

**Comment by Nenirey** [comment]
I will think about it  and i recomend you the uGet download manager

Thanks to use and happy holidays.
