### ISSUE TITLE
[Sugerencia | Pregunta] Descarga Selectiva con aria2

### ISSUE THREAD

**Issue by GATOQSECOMIO** [Nenirey/AWGG#15]
¿Es posible la descarga selectiva del contenido de un torrent con AWGG? ¿Tienes pensado implementarlo?

Felicidades por el proyecto.
Gracias.

**Comment by Nenirey** [comment]
Saludos, la funcion no está implementada en la interfaz gráfica, pero recuerda que a lo hora de añadir una descarga hay un apartado para pasarle parametros adicionales al motor de descargas, tal vez ahi puedas pasarle un comando para descargar solo el archivo que quieres.

Gracias por usar AWGG

**Comment by GATOQSECOMIO** [comment]
Gracias por responder tan rápido. Actualmente estoy revisando este contenido. No entiendo mucho de introducir líneas de  código, pero hasta donde he podido entender, primero debes dar orden de visualizar los archivos del .torrent y posteriormente elegir los archivos concretos de interés. Cierro incidencia. Gracias
[Downloading individual files from torrent #843](https://github.com/aria2/aria2/issues/843)
