### ISSUE TITLE
Update Packages/Engines for 0.6.0 BETA

### ISSUE THREAD

**Issue by ghost** [Nenirey/AWGG#9]
Packages/Engines needed to be updated to the latest version
Many tools has been updated within this time like `youtube-dl` and `others`
Update your packages/engines to latest version at https://github.com/Nenirey/AWGG-UPDATES to make it up-to-date

**Comment by MithilMajumder** [comment]
Update Check fails. Failed to update  latest internal packages through newer versions are available

**Comment by Nenirey** [comment]
Done!
